name: Continuous Integration

on:
  push:
    branches:
      - main
      - '**'

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    environment: dev 
    env:
      CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
      CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
      CYPRESS_BASE_URL: ${{ vars.CYPRESS_BASE_URL }}
      CYPRESS_API_BASE_URL: ${{ vars.CYPRESS_API_BASE_URL }}
      CYPRESS_INVALID_USERNAME: ${{ vars.CYPRESS_INVALID_USERNAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: |
          echo "CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}"
          echo "CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}"
          echo "CYPRESS_BASE_URL: ${{ vars.CYPRESS_BASE_URL }}"
          echo "CYPRESS_API_BASE_URL: ${{ vars.CYPRESS_API_BASE_URL }}"
          echo "CYPRESS_INVALID_USERNAME: ${{ vars.CYPRESS_INVALID_USERNAME }}"
          npm run cypress:run:ci

      - name: Generate Allure Report
        if: always()
        run: npm run allure:generate

      - name: Upload Allure Report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report