name: Continuous Integration

on:
  push:
    branches:
      - main
      - '**'

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    env:
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}
      invalidUsername: ${{ vars.INVALID_USERNAME }}
      apiBaseUrl: ${{ vars.API_BASE_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: |
          echo "The USERNAME is ${{ secrets.USERNAME }}"
          echo "The PASSWORD is ${{ secrets.PASSWORD }}"
          echo "The INVALID_USERNAME is ${{ vars.INVALID_USERNAME  }}"
          echo "The API_BASE_URL is ${{ vars.API_BASE_URL }}"
          npm run cypress:run
        

      - name: Generate Allure Report
        if: always()
        run: npm run allure:generate

      - name: Upload Allure Report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Allure Results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results